FROM alpine:latest

CMD ["echo 'My name is Digvijay' && echo 'Few technologies I am learning this year are:' && echo '1. Docker' && echo '2. Kubernetes' && echo '3. Terraform' && echo '4. AWS'"]

ENTRYPOINT ["/bin/sh", "-c"]