name: databricks-test

on:
  workflow_dispatch:
#    inputs:
#      test-input:
#        type: string
#        required: true
#        description: "Input String to test"

jobs:
  databricks:
    runs-on: ubuntu-latest
    steps:
#      - name: test-input
#        env:
#          regex: '^[^,].*[^,]$'
#        run: |
#          [[ ${{ inputs.test-input }} =~ ${{ env.regex }} ]]

      - name: configure databricks
        env:
          DATABRICKS_HOST: https://test-url.databricks.com
          DATABRICKS_TOKEN: test-token
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version
          echo "[DEFAULT]" >> .databrickscfg
          echo "host = ${{ env.DATABRICKS_HOST }}" >> .databrickscfg
          echo "token = ${{ env.DATABRICKS_TOKEN }}" >> .databrickscfg
          cat .databrickscfg

      - name: test
        run: |
          cat .databrickscfg
