name: databricks-test

on:
  workflow_dispatch:
#    inputs:
#      test-input:
#        type: string
#        required: true
#        description: "Input String to test"

jobs:
  databricks:
    runs-on: ubuntu-latest
    steps:
#      - name: test-input
#        env:
#          regex: '^[^,].*[^,]$'
#        run: |
#          [[ ${{ inputs.test-input }} =~ ${{ env.regex }} ]]

      - name: install-databricks-cli
        run: |
          curl -V
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: test
        run: |
          databricks -v
          databricks version
