name: Dispatch Inputs

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Boolean input 1'
        type: boolean
        required: true
      input2:
        description: 'Boolean input 2'
        type: boolean
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add Boolean Inputs to Array
        run: |
          python3 .github/scripts/parse-input.py
          test="${{ toJson(inputs) }}"
          echo $test
          migration_configs=$(echo '${{ toJson(inputs) }}' | jq -r 'to_entries[] | select(.value == true) | .key' | paste -sd ',' -)
          echo $migration_configs